#!/bin/bash

printf "### Removing old container\n"
docker kill youtube-comment-web
docker rm youtube-comment-web

printf "\n### Building Container...\n"
docker build -t youtube-comment-web .

printf "\n### Starting Container...\n"
docker run -d -p 49161:3000 -e "NODE_ENV=production" --restart=always --name youtube-comment-web youtube-comment-web

printf "\n\n### Result:\n"
docker ps --filter=[name=youtube-comment-web]
